global:
  scrape_interval: 15s # Cứ 15 giây lấy dữ liệu một lần

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308'] 
      # 'kafka-exporter' là tên service trong docker-compose bên dưới